#!/bin/bash

# Example content for requirements.txt
requirements_content='Flask==0.12  # Vulnerable to directory traversal
requests==2.19.1  # Vulnerable to open redirect (CVE-2018-18074)
urllib3==1.24.1  # Vulnerable to DoS (CVE-2019-11324)
django==1.11.20  # Vulnerable to SQL injection (CVE-2019-14234)
jinja2==2.10  # Vulnerable to sandbox escape attacks (CVE-2019-10906)
cryptography==2.1.4  # Memory leak vulnerability (CVE-2018-10903)
pillow==6.2.0  # Multiple buffer overflow vulnerabilities (CVE-2019-16865)
PyYAML==3.13  # Arbitrary code execution during deserialization (CVE-2017-18342)
SQLAlchemy==1.2.17  # SQL injection vulnerability (CVE-2019-7548)'

# Example content for yarn.lock
yarn_lock_content='# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

"@babel/code-frame@^7.0.0":
  version "7.10.4"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.10.4.tgz#e62acef1de501e91a7c26e9d7d972df3a5b36645"
  integrity sha512-27mGDXBbjRBnCzHmeG1M8XwrZMO+Jc1/HgiYF/nYlbz8Vf8lcnHVRAl0V3KmbfpwQUaPIsfksabgaYMa8jN5Zg==
  dependencies:
    "@babel/highlight" "^7.10.4"

"@babel/highlight@^7.10.4":
  version "7.10.4"
  resolved "https://registry.yarnpkg.com/@babel/highlight/-/highlight-7.10.4.tgz#523b01af6648533b31374b65714fcabd4b813fc0"
  integrity sha512-9LW9WWsueakfS/UpQ7odWx4Gk7/CEQ+vKmbWJ+gbKmXVUTiTADckIbvtiubV0jT74rsdd07unGcxXSdYb+okDw==
  dependencies:
    "@babel/helper-validator-identifier" "^7.10.4"
    chalk "^2.0.0"'



# Example content for pnpm-lock.yaml
pnpm_lock_content='lockfileVersion: '6.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .: {}

  packages/serviceA:
    dependencies:
      moment:
        specifier: 2.29.4
        version: 2.29.4

  packages/serviceB:
    dependencies:
      moment:
        specifier: 2.24.0
        version: 2.24.0

packages:

  /moment@2.24.0:
    resolution: {integrity: sha512-bV7f+6l2QigeBBZSM/6yTNq4P2fNpSWj/0e7jQcy87A8e7o2nAfP/34/2ky5Vw4B9S446EtIhodAzkFCcR4dQg==}
    dev: false

  /moment@2.29.4:
    resolution: {integrity: sha512-5LC9SOxjSc2HF6vO2CyuTDNivEdoz2IvyJJGj6X8DJ0eFyfszE0QiEd+iXmBvUP3WHxSjFH/vIsA0EN00cgr8w==}
    dev: false'

# Example content for package-lock.json
package_lock_content='{
  "name": "example-project",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "dependencies": {
    "requests": {
      "version": "2.19.1",
      "resolved": "https://registry.npmjs.org/requests/-/requests-2.19.1.tgz",
      "integrity": "sha512-abc123...",
      "requires": {
        "urllib3": "1.24.1"
      }
    },
    "urllib3": {
      "version": "1.24.1",
      "resolved": "https://registry.npmjs.org/urllib3/-/urllib3-1.24.1.tgz",
      "integrity": "sha512-def456..."
    },
    "lodash": {
      "version": "4.17.11",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.11.tgz",
      "integrity": "sha512-ghi789..."
    }
  }
}'

# Populate requirements.txt files
find . -name "requirements.txt" | while read -r file; do
  echo "Populating $file with example content for requirements.txt..."
  echo "$requirements_content" > "$file"
done

# Populate yarn.lock files
find . -name "yarn.lock" | while read -r file; do
  echo "Populating $file with example content for yarn.lock..."
  echo "$yarn_lock_content" > "$file"
done

# Populate pnpm-lock.yaml files
find . -name "pnpm-lock.yaml" | while read -r file; do
  echo "Populating $file with example content for pnpm-lock.yaml..."
  echo "$pnpm_lock_content" > "$file"
done


echo "All requirements.txt and yarn.lock files have been populated!"

