name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci --supply-chain --exclude='package-lock.json'
